### ISSUE TITLE
Error executing Crystal plugin. spawn crystal ENOENT

### ISSUE THREAD

**Issue by girng** [crystal-lang-tools/vscode-crystal-lang#102]
I tried `crystal.bat`, and the `shell: "bash"` change inside `crystalUtils.ts`

Both of those modifications will remove the `Error executing Crystal plugin. spawn crystal ENOENT` error, but the formatting does not happen. Not sure what else to try :O

I have https://github.com/faustinoaq/crystal-windows-installer

`crystal env` : 
```
CRYSTAL_CACHE_DIR="/home/nick/.cache/crystal"
CRYSTAL_PATH="/usr/bin/../share/crystal/src:lib"
CRYSTAL_VERSION="0.31.1"
CRYSTAL_LIBRARY_PATH="/usr/bin/../lib/crystal/lib"
```

VSCode:
```
[Window Title]
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

I just reinstalled Windows 10 and before this, VSCode with this plugin was working fine. Hmmm...

**Comment by nobodywasishere** [comment]
If you can, please test this out on v0.9.0 to see if this is still an issue
