### ISSUE TITLE
Weird syntax highlighting

### ISSUE THREAD

**Issue by andraantariksa** [crystal-lang-tools/vscode-crystal-lang#105]
![Screenshot_2020-02-29_16-25-39](https://user-images.githubusercontent.com/9760691/75604920-51e83c00-5b10-11ea-91ad-31b8a81fe11a.png)

**Comment by faustinoaq** [comment]
Hi @andraantariksa 

I can confirm the weird syntax in `(two_byte << 8) | (two_byte >> 8)`

Here some captures:

Right behavior?  https://carc.in/#/r/8t1b

![image](https://user-images.githubusercontent.com/3067335/78003218-f4f1c880-72fd-11ea-9482-9df1ea26578e.png)

VSCode Default Dark+ Theme

![image](https://user-images.githubusercontent.com/3067335/78003342-1c489580-72fe-11ea-90db-96da28aecb14.png)

VSCode One Dark Pro Theme

![image](https://user-images.githubusercontent.com/3067335/78003405-34201980-72fe-11ea-890b-e088b3ed6d02.png)

VSCode One Dark Theme

![image](https://user-images.githubusercontent.com/3067335/78003485-55810580-72fe-11ea-8909-69404d0452be.png)

I think this may be some issue with [crystal.json](https://github.com/crystal-lang-tools/vscode-crystal-lang/blob/master/syntaxes/crystal.json) converted from [Crystal.tmLanguage](https://github.com/crystal-lang-tools/sublime-crystal/blob/master/Crystal.tmLanguage)

I tested this extension using `Crystal.tmLanguage` and looks like this:

![image](https://user-images.githubusercontent.com/3067335/78004127-4f3f5900-72ff-11ea-8141-fbce98f3a3a7.png)

VSCode Dark+ theme:

![image](https://user-images.githubusercontent.com/3067335/78004264-7bf37080-72ff-11ea-9f99-62b93431d9a3.png)


VSCode One Dark Pro Theme:

![image](https://user-images.githubusercontent.com/3067335/78004303-8a418c80-72ff-11ea-9a70-7eb4536096a7.png)


VSCode One Dark Theme:

![image](https://user-images.githubusercontent.com/3067335/78004358-9f1e2000-72ff-11ea-98f5-50ff6e280cc2.png)

A workaround could be replacing `crystal.json` by original `Crystal.tmLanguage` based on Ruby.

WDYT?

**Comment by andraantariksa** [comment]
The first one looks better for me. From what I see in C++ language syntax highlighting, the variable that coming from function argument will be in red color and the other variable will be in white.

VSCode One Dark Pro Theme

[![https://imgur.com/o5RJItX.png](https://imgur.com/o5RJItX.png)](https://imgur.com/o5RJItX.png)
