### ISSUE TITLE
Windows WSL hover not work at all

### ISSUE THREAD

**Issue by huuhait** [crystal-lang-tools/vscode-crystal-lang#106]
Hi i'm using windows and i have install crystal and scry in my wsl

but when i hover a func it showing up and close after 0.01s or faster

here is my config:
```
{
"crystal-lang.compiler": "crystal.bat",
    "crystal-lang.server": "scry.bat",
    "crystal-lang.shards": "shards.bat",
    "crystal-lang.completion": true,
    "crystal-lang.hover": true,
    "crystal-lang.implementations": true,
    "crystal-lang.bashOnWindows": true,
    "crystal-lang.mainFile": "${workspaceRoot}/app/app.cr",
}
```

**Comment by faustinoaq** [comment]
Hi @huuhai

> but when i hover a func it showing up and close after 0.01s or faster

It can be a crystal.bat error happening in the background, so it prevents the extension of working properly.

BTW The Crystal compiler doesn’t run on Windows yet. WSL (compatibility-layer) may have some issues sometimes when executing it from vscode. Currently, I'm using [Microsoft Remote](https://github.com/Microsoft/vscode-remote-release) to develop with crystal on my ubuntu server from my windows machine. It works like a charm! 💯 

![Annotation 2020-03-31 021434](https://user-images.githubusercontent.com/3067335/78001997-22d60d80-72fc-11ea-86b6-1cda733539a3.png)

**Comment by huuhait** [comment]
tks u
it working good for me :D
