### ISSUE TITLE
Block should not add arguments by default

### ISSUE THREAD

**Issue by MatheusRich** [crystal-lang-tools/vscode-crystal-lang#108]
Not every block has args, but the `do` shortcut always adds them. This is specially cumbersome when creating specs.

I suggest that the `do` shortcut just add a basic block. For blocks with args, we could use `dop` (as the ruby vscode extension does).

I can provide a PR if this is ok.

**Comment by faustinoaq** [comment]
Hi @MatheusRich  Great idea 👍
