### ISSUE TITLE
Prevent focus stealing when there' scry error

### ISSUE THREAD

**Issue by iambudi** [crystal-lang-tools/vscode-crystal-lang#110]
Is it possible to disable **focus stealing** to the Output Tab when scry throws errors in VSCode panel? 
It's quite annoying 😉. I tried to hide the the Tab Output but it always come back.
Thanks.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/31809529/79625979-e8bb9700-8156-11ea-943b-f3b9ad42c479.png">

**Comment by faustinoaq** [comment]
@iambudi Thank you for reporting this issue!

I think we can adjust the log handler to be more silent

Did you download a scry executable [here](https://github.com/crystal-lang-tools/scry/releases)? or Did you compile it by yourself?

**Comment by iambudi** [comment]
@faustinoaq I compiled by myself. Thanks.
