### ISSUE TITLE
Task launch gets stuck on "Fetching build task"

### ISSUE THREAD

**Issue by lbarasti** [crystal-lang-tools/vscode-crystal-lang#111]
if I update the VS extension to the latest version (0.4.0), and launch a task - e.g. a crystal run task - the task won't start, and the loading spinner for "Fetching build task" will keep on... spinning.
I'm on VS 1.44.2 running on Ubuntu 19.10

![image](https://user-images.githubusercontent.com/782103/79643597-a8cad300-819b-11ea-8abf-7045940163a3.png)

Running tasks without any vscode-crystal extension works just fine, as well as running tasks with v0.3.14 of the extension.

@faustinoaq mentioned that this issue might be due to the task provider implementation not working properly, see https://github.com/crystal-lang-tools/vscode-crystal-lang/pull/77

**Comment by faustinoaq** [comment]
Hi @lbarasti Thank you for reporting this issue!

I'm already trying to fix it :)

**Comment by grioja** [comment]
Also running into this problem!

**Comment by vypxl** [comment]
Any updates on this? It seems like this only happens when the visible editor is a crystal-related file.

**Comment by grioja** [comment]
Can we at least pull `0.4.0` from the official releases until this is fixed? It keeps auto-upgrading to this version that has this broken behavior.

**Comment by nobodywasishere** [comment]
Let me know if this still occurs on v0.9.0
