### ISSUE TITLE
Wrong syntax highlighting on ECR

### ISSUE THREAD

**Issue by MatheusRich** [crystal-lang-tools/vscode-crystal-lang#112]
A weird one on ECR:
![image](https://user-images.githubusercontent.com/20938712/79670690-4a9df000-819b-11ea-85f1-d7c2d39bb036.png)

Using the ERB highlighting:
![image](https://user-images.githubusercontent.com/20938712/79670725-7325ea00-819b-11ea-99f4-71d6a91e7098.png)

I'm using the One Dark PRO theme

**Comment by redcodefinal** [comment]
My issue may be related #128

**Comment by redcodefinal** [comment]
@asterite confirmed fixed my issue #128 with #129 , but it didn't fix this issue. I can confirm it is still present.

**Comment by asterite** [comment]
Of course, it doesn't seem to be related to string interpolation :-)

I'll see if I can see what's going on...

**Comment by asterite** [comment]
It would have been helpful to have the textual thing, not an image... oh well...

**Comment by asterite** [comment]
I won't fix it but your best bet is to copy this one from Ruby and adapt it to Crystal: https://github.com/rubyide/vscode-ruby/blob/master/packages/vscode-ruby/syntaxes/erb.cson.json

**Comment by MatheusRich** [comment]
Another one: `%w` is not interpreted as string.

Crystal:
![image](https://user-images.githubusercontent.com/20938712/97442022-266c5a00-1908-11eb-9b1b-a6e3d7a3481b.png)

Ruby:
![image](https://user-images.githubusercontent.com/20938712/97442045-2c623b00-1908-11eb-9b9e-3d0d19b44974.png)

Here's the code:
```crystal
%w[some WORDS in HERE]
```

**Comment by asterite** [comment]
Thank you! But these are all different bugs, I would open separate issues for them.

**Comment by MatheusRich** [comment]
@asterite I thought it would make sense to keep this Highlight issues together, but I'll open another issue. Thanks!

**Comment by maxbertinetti** [comment]
@MatheusRich can you please provide a sample file to see the situation about this ticket?

**Comment by MatheusRich** [comment]
@maxbertinetti Just type `%w[some WORDS in HERE]` and you got it.

**Comment by MatheusRich** [comment]
@maxbertinetti here it is:

```ecr
<% (1..10).each do |index| %>
  <tr class="<%= index.odd? ? "odd" : "even" %>">
<% end %>
```

**Comment by maxbertinetti** [comment]
I think is not correct the way you are trying to render this. You must use single quote outside and double inside.

BTW in [v0.8.2](https://github.com/crystal-lang-tools/vscode-crystal-lang/releases/tag/v0.8.2)

![image](https://user-images.githubusercontent.com/26814295/114673235-42bd5100-9d06-11eb-9d68-bc318201ae7d.png)
