### ISSUE TITLE
Supporting Windows for Crystal VS Code extensions

### ISSUE THREAD

**Issue by rishavs** [crystal-lang-tools/vscode-crystal-lang#113]
With the basic windows compiler done for Crystal, we should now look at actually being able to use the language on that platform. Right now, the VS Code extension doesn't provides meaningful autocomplete and error handling which are probably the 2 most important IDE features.

I understand that there is still a lot of work left to make Crystal windows-native, but maybe we can list down the pieces that are needed for the VS Code extensions to work on Windows, so as to better gauge where we stand and what work needs to be done to get there.

**Comment by maxbertinetti** [comment]
Hi @rishavs.

I don't have (and don't want to use) Windows.

Please try last plugin version with [crystalline](https://github.com/elbywan/crystalline) and report any problems.

If it is possible for you, compare with Linux or Mac behaviour.
If they behave differently we can make a plan to pair the versions.

**Comment by maxbertinetti** [comment]
Close because missing informations
