### ISSUE TITLE
Compiler warning parsed in output

### ISSUE THREAD

**Issue by kingsleyh** [crystal-lang-tools/vscode-crystal-lang#123]
When Scry is used it looks like it's parsing the Warning message from the compiler and then cannot continue. I didn't find a way to suppress that warning when building.

```
[Error - 10:14:56 AM] A error was found while searching implementations
Unexpected char 'W' at 1:1
Warning: Gzip is deprecated, use Compress::Gzip
```

**Comment by maxbertinetti** [comment]
I'm not sure if the problem is related to the VSCode plugin or scry. I have a look at this on the week end.

**Comment by maxbertinetti** [comment]
@kingsleyh have you tried [Cristalline](https://github.com/elbywan/crystalline) instead of Scry

**Comment by kingsleyh** [comment]
oh I never heard of it lol - is Scry dead then?

**Comment by maxbertinetti** [comment]
I don't find none of the contributor active looking at it. Instead the Crystalline project is working, active and very promising!
