### ISSUE TITLE
Code Helper process showing 200-300% CPU usage on MacOS

### ISSUE THREAD

**Issue by ajith-joseph** [crystal-lang-tools/vscode-crystal-lang#127]
I have setup the vscode extension (v 0.6.1) with crystalline language server on my Mac (v 10.13.6). 
CPU is running hot. I use other lang extensions like Golang where I don't see this issue.
![image](https://user-images.githubusercontent.com/8683507/95692682-5adbd880-0bdc-11eb-91b9-afb2d2206392.png)

**Comment by maxbertinetti** [comment]
This is a Crystalline issue more then a VSCode plugin issue.

**Comment by elbywan** [comment]
For the record, I doubt that crystalline is the culprit. See: https://github.com/microsoft/vscode/issues/108441

**Comment by maxbertinetti** [comment]
> For the record, I doubt that crystalline is the culprit. See: [microsoft/vscode#108441](https://github.com/microsoft/vscode/issues/108441)

Sorry, what I mean is that is not something that can be caused by this plugin since is not hungry in resources, better to know that the problem is neither in Crystalline too.

**Comment by elbywan** [comment]
> Sorry, what I mean is that is not something that can be caused by this plugin since is not hungry in resources, better to know that the problem is neither in Crystalline too.

No worries 😄 ! I just wanted to post a link to the solution just in case people stumble upon this issue in the future.
