### ISSUE TITLE
%w is not interpreted as string.

### ISSUE THREAD

**Issue by MatheusRich** [crystal-lang-tools/vscode-crystal-lang#130]
Crystal:
![image](https://user-images.githubusercontent.com/20938712/97442022-266c5a00-1908-11eb-9b1b-a6e3d7a3481b.png)

Ruby:
![image](https://user-images.githubusercontent.com/20938712/97442045-2c623b00-1908-11eb-9b9e-3d0d19b44974.png)

Here's the code:
```crystal
%w[some WORDS in HERE]
```

**Comment by maxbertinetti** [comment]
Closed in [v0.8.2](https://github.com/crystal-lang-tools/vscode-crystal-lang/releases/tag/v0.8.2)

![image](https://user-images.githubusercontent.com/26814295/114671858-d7bf4a80-9d04-11eb-895f-7429d0960c72.png)
