### ISSUE TITLE
Publish to open-vsx

### ISSUE THREAD

**Issue by GeopJr** [crystal-lang-tools/vscode-crystal-lang#131]
Hi, would it be possible for the extension to get published on [OpenVsx](https://open-vsx.org/)?
OpenVsx is an alternative marketplace used by [VSCodium](https://vscodium.com/).

Instructions can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension).

Similar issue: https://github.com/crystal-lang-tools/vscode-crystal-lang/issues/120

Currently the only way to install this extension is by either downloading it from the marketplace website or by modifying the `extensionsGallery` section of the `product.json` file.

Thanks!

**Comment by maxbertinetti** [comment]
It's doable.
I think I can do it in the next days and finally automating the deploy with Github action for all two Marketplaces.

**Comment by maxbertinetti** [comment]
@GeopJr I decided to wait until 9th December, read [here](https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management)

@bcardiff I think you have to register as Organization there like for VS Marketplace.

**Comment by bcardiff** [comment]
Publisher claimed at https://github.com/eclipse/open-vsx.org/issues/217

**Comment by bcardiff** [comment]
I've just manually published 0.6.2 in https://open-vsx.org/extension/crystal-lang-tools/crystal-lang

@maxbertinetti I leave a OPEN_VSX_TOKEN secret in this repo configured to automate the publishing.

If you create a user in open-vsx I can add you to the crystal-lang-tools namespace there.

**Comment by maxbertinetti** [comment]
@bcardiff I created a user with my Github Account.
This week end I start building the Github Action to automate the deploy on the two Marketplace on a new release on master

**Comment by bcardiff** [comment]
Cool. I've just added you to the open-vsx publisher

**Comment by maxbertinetti** [comment]
@bcardiff please I need a token also for VS Code Marketplace (VS_MARKETPLACE_TOKEN) so that I can deploy automatically also there when ready
