### ISSUE TITLE
Wrong syntax highlighting when symbol name is equal to a keyword

### ISSUE THREAD

**Issue by MatheusRich** [crystal-lang-tools/vscode-crystal-lang#133]
![image](https://user-images.githubusercontent.com/20938712/99617012-21796280-29fd-11eb-9a23-cb60e3563dfa.png)

Code:

```crystal
KEYWORDS = {
  and:    :AND,
  else:   :ELSE,
  false:  :FALSE,
  fn:     :FN,
  if:     :IF,
  let:    :LET,
  nil:    :NIL,
  or:     :OR,
  print:  :PRINT,
  puts:   :PUTS,
  return: :RETURN,
  true:   :TRUE,
  while:  :WHILE,
}

def something(**args)
  puts args
end

something(if: 1, else: 2, nil: 3, other: 4)
```

**Comment by grantspeelman** [comment]
not sure if this is related as well

![Screenshot_20210102_122828](https://user-images.githubusercontent.com/98919/103449025-13a24700-4cf6-11eb-8ef2-80cf84a6c467.png)

**Comment by maxbertinetti** [comment]
![carbon(1)](https://user-images.githubusercontent.com/26814295/109390181-59534880-7910-11eb-95c8-2827c5b1214b.png)

![carbon](https://user-images.githubusercontent.com/26814295/109390190-640ddd80-7910-11eb-8ea7-d88719c7be82.png)

This is some syntax highlighting coming from carbon.sh.
Can you confirm @MatheusRich  @grantspeelman that is the desired behaviour?

I'm studying the grammar it uses for Crystal.
The format is completely different.

If someone can help on this would be great!

**Comment by grantspeelman** [comment]
That looks Good to me 👍🏽
