### ISSUE TITLE
macOS BigSur - .cache directory is getting created under the project directory

### ISSUE THREAD

**Issue by tuxaanand** [crystal-lang-tools/vscode-crystal-lang#142]
**Describe the bug**
The cache files produced for the sources scanned are getting created under the project directory - {project}/Users/{user}/.cache/crysta on macOS BigSur

**To Reproduce**
1. Open a project folder with crystal sources
2. A folder called 'Users' with the cache directory structure within that

**Expected behavior**
The cache directory should be created under the user's home directory

**Screenshots**
<img width="1680" alt="Screenshot 2021-04-14 at 12 28 43 PM" src="https://user-images.githubusercontent.com/9750371/114667546-35f82780-9d1d-11eb-9bff-7c0b684f365a.png">

**Desktop (please complete the following information):**
 - OS: macOS BigSur
 - Crystal version: 1.0.0
 - This plugin version: 0.8.2

**Comment by maxbertinetti** [comment]
@tuxaanand I need some further info

- Are you using an Intel machine?
- The project was created with crystal init...?
- VS Code version?

**Comment by maxbertinetti** [comment]
I cannot reproduce the bug.

![image](https://user-images.githubusercontent.com/26814295/114670768-a8f4a480-9d03-11eb-9599-81efc90ec168.png)
![image](https://user-images.githubusercontent.com/26814295/114670824-b447d000-9d03-11eb-9abf-d26efa8599cd.png)
![image](https://user-images.githubusercontent.com/26814295/114670889-c295ec00-9d03-11eb-9f45-28380983697f.png)
![image](https://user-images.githubusercontent.com/26814295/114670921-caee2700-9d03-11eb-850f-323321b67e37.png)
![image](https://user-images.githubusercontent.com/26814295/114671087-fd981f80-9d03-11eb-8e50-1008b145e3f0.png)
![image](https://user-images.githubusercontent.com/26814295/114671249-2b7d6400-9d04-11eb-9cba-368ab30b5cb8.png)

Verify there's no .cache/crystal in home directory
Try remove the cache directory from the project

Also...I don't understand how this can be a plugin bug.
