### ISSUE TITLE
Heredoc syntax highlighting is incorrect

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang-tools/vscode-crystal-lang#149]
* Everything after the heredoc start delimiter is not highlighted. Those characters are never part of the heredoc, so they should receive regular highlighting.
* If there are multiple heredocs created on the same line, only the first end delimiter is highlighted and subsequent heredocs are highlighted as if they are regular code.

![Screenshot_20211006_002204](https://user-images.githubusercontent.com/1361918/136063219-56ca87a4-c7b5-4e76-ac16-e2682a3a0e24.png)

For comparison, here is how the same code looks like in Ruby:

![Screenshot_20211006_002300](https://user-images.githubusercontent.com/1361918/136063365-8aa97a78-9e7d-4c33-8067-5e21681919aa.png)

(It appears they use only the last heredoc name as the delimiter for all heredocs that immediately follow.)

**Comment by nobodywasishere** [comment]
I don't think this is possible to fix without tree-sitter or an LSP, due to the complexity of Heredocs.
