### ISSUE TITLE
Type and method introspection not working

### ISSUE THREAD

**Issue by divmgl** [crystal-lang-tools/vscode-crystal-lang#152]
So I've defined an argument of type `String` in my function:

```crystal
module Jackd::Validation
  def validate_tube_name(name : String)
  end
end
```

But when I go to use the `name` variable, I get these class `Object` methods available to me:

<img width="419" alt="Screen Shot 2022-04-29 at 1 13 26 PM" src="https://user-images.githubusercontent.com/5452298/165991711-b3b83bd3-ae85-4a09-af85-c9ca72303f8f.png">

What's also weird is that when I go to use one of these methods, I have no details as to the parameters these methods accept:

<img width="104" alt="Screen Shot 2022-04-29 at 1 14 01 PM" src="https://user-images.githubusercontent.com/5452298/165991802-18ff0d8f-5ad7-48c7-be61-5f1bafbccf6f.png">

It's just blank. 

**Expected behavior**
1. I can see all of the methods that are available to `String` objects in the stdlib.
2. When using a method, I can see its parameters and any comments for those parameters.

**Desktop (please complete the following information):**
 - OS: macOS
 - Crystal version: Crystal 1.4.1 (2022-04-22)
 - This plugin version: 0.6.0

**Comment by nobodywasishere** [comment]
Are you using Crystalline? If not I'm not sure if method autocomplete is within the scope of this extension, as it will require something on the level of an LSP to accomplish
