### ISSUE TITLE
error requiring "prelude" on windows 

### ISSUE THREAD

**Issue by HOMODELUNA** [crystal-lang-tools/vscode-crystal-lang#153]
# error requiring "prelude" on windows 
It goes out every time in a crystal file, blocking sequencial analysis
```
can't find file 'prelude'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
```
Here is my version and environment
```
PS C:\Users\homodeluna\Desktop> crystal env
CRYSTAL_CACHE_DIR=C:\Users\homodeluna\AppData\Local\crystal\cache
CRYSTAL_PATH=E:\lang\Crystal\src
CRYSTAL_VERSION=1.5.0
CRYSTAL_LIBRARY_PATH=E:\lang\Crystal\lib
CRYSTAL_OPTS=""

PS C:\Users\homodeluna\Desktop> crystal version
Crystal 1.5.0 [994c70b10] (2022-07-06)

LLVM: 13.0.0
Default target: x86_64-pc-windows-msvc
```

**Screenshot
![error](https://user-images.githubusercontent.com/72009635/187148451-cfd8da18-4666-43ea-9961-2d026aad253c.png)
s**

**Comment by nobodywasishere** [comment]
A few questions:
- Are you using crystalline?
- Have you tried a newer / different version of the compiler?
- Does crystal work via the command line, for building your program?

**Comment by HOMODELUNA** [comment]
@nobodywasishere 
- I'm not using crystalline,I was using scry v0.9.1,and it doesn't response to any of my requests, nor does it report error. So I removed it.
- I've updated my crystal to v1.8.2, and the situation now is as above
- command line crystal works just fine

**Comment by nobodywasishere** [comment]
Can you let me know if this still occurs on v0.9.0?
