### ISSUE TITLE
How to autoformat on save?

### ISSUE THREAD

**Issue by alanwilter** [crystal-lang-tools/vscode-crystal-lang#162]
Is this property there?

When I save I was expecting the code to be formatted, like removing trimming whitespace, add the space where needed, etc.

Or maybe I'm too used to python + black and crystal has nothing close to it?

**Comment by nobodywasishere** [comment]
There's a setting in VSCode to turn this on (either at the User level or you can set it per workspace). I just tested and it worked perfectly. See [this StackOverflow post](https://stackoverflow.com/questions/39494277/how-do-you-format-code-on-save-in-vs-code).
