### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang-tools/vscode-crystal-lang#174]
The last release 0.8.4 was added on `2022-1-27, 11:51:14`. Since that release was tagged, there's been several updates made (18 commits), including a few (https://github.com/crystal-lang-tools/vscode-crystal-lang/pull/165, https://github.com/crystal-lang-tools/vscode-crystal-lang/pull/173) PRs that may be ready to go.

I've never released a plugin for VSCode, so I'm not sure how involved it is, but I would like to at least get the conversation started on what all it might take to get a new release out. Or maybe a beta release to test out all of these changes? 

Thank you!

**Comment by nobodywasishere** [comment]
I've been working on testing the current code to make sure everything works across the various platforms before release (linux, windows, macos) and to debug issues people have ran into. I've conversed with @bcard

**Comment by jwoertink** [comment]
Awesome! That's great to hear :rocket:  Thanks for the update :heart:

**Comment by nobodywasishere** [comment]
Thank you as well for reaching out! I'll use this issue for keeping track of the upcoming release.

**Comment by nobodywasishere** [comment]
As part of helping me test this for release, I put together a list of features, short descriptions, how they work at a high level, and known current issues. Eventually I want to work this into the wiki, but for now it's a good starting point for what to test to ensure everything works. If anyone is up to help assist in testing this before release, I've attached a development version of the current changes on #173.

[crystal-lang-0.8.5.vsix.zip](https://github.com/crystal-lang-tools/vscode-crystal-lang/files/12309021/crystal-lang-0.8.5.vsix.zip)

## Features

- Syntax highlighting
    - Description
        - Highlights Crystal source code in '*.cr' files as well as in Markdown code blocks.
        - Also highlights template files such as ECR and Slang.
    - How it works
        - A series of regex's in a TextMate grammar that match language constructs.
    - Potential problems
        - Heredoc's are currently broken

- Auto indentation
    - Description
        - Auto-indents as code is typed into the editor based on the code being typed.
    - How it works
        - Two regex's in the main file which determine when to indent and when to de-indent
    - Potential problems
        - `include` is currently mistaken as `in` and is de-indented when it is not supposed to

- Snippets
    - Description
        - A series of small code completions for common use cases, such as `begin` expanding to include a rescue and an end statement
    - How it works
        - A JSON file for completions for Crystal, ECR, and Slang, which have a "prefix" to look for, and a "body" to replace it with
        - Replacement happens immediately
    - Potential problems
        - May come across situations where a snippet is activated where the developer did not intend for it to happen, leading to frustration and a worse experience
        - Some of the snippets don't work, such as ECR ones with symbol prefixes

- Formatting
    - Description
        - A vscode command that will automatically format your code using the Crystal formatter built into the compiler itself
        - Can also format automatically on save
    - How it works
        - The code from the current file is copied and sent through the compiler's formatting tool, returning the formatted code
        - Is very fast as it only operates on one file
    - Potential problems
        - If the code is not proper source (some bug or issue), the formatter will not do anything or return an error

- Problems finder
    - Description
        - Automatically compiles the source code when a file is open or saved to find issues without needing to run the compiler manually
    - How it works
        - Grabs the source code and tries building it. If it runs into an issue, the issue is reported to a VSCode diagnostic collection
    - Potential problems
        - Constantly running Crystal in the background can be slow and use a lot of resources
        - Speed depends on how much the compiler has to run before finding issues

- Document Symbols
    - Description
        - Allows for easier code navigation through breadcrumbs at the top of the file, as well as being viewable via a keyboard shortcut
    - How it works
        - A file is manually parsed using regex's line by line, creating symbols where they're found
    - Potential problems
        - Very slow and error prone
        - Will not work if mainFile is not set
        - Does not seem to work in general

- Peek and go to definition
    - Description
        - Allows for quickly jumping to the definition of a method
    - How it works
        - Spawns the implementations tool built into the Crystal compiler to find the locations of definitions
    - Potential problems
        - Very slow as it calls the compiler every time
        - Sometimes doesn't do anything
        - Will not work if mainFile is not set

- Show symbol information on hover
    - Description
        - Will provide information on a piece of code when hovering the mouse
    - How it works
        - When hovering, the place in code is captured and passed off to the Crystal compiler's context tool, which returns the information from it
    - Potential problems
        - Sometimes doesn't provide much information, especially for non-stdlib stuff such as methods within the same codebase

- Method completion for Literals and Symbols
    - Description
        - Provides code completions, allowing the developer to know what methods are available on an object
    - How it works
        - Calls the Crystal context tool and parses the output
    - Potential problems
        - Doesn't provide completions for several objects, but does for File and Dir objects

- Tasks
    - Description
        - Allow a quick way of executing various tasks in VSCode projects
    - How it works
        - Calls the task in the background when executed, output shown in a temporary terminal
    - Potential problems

## Platform Support Goal (at minimum)

- Linux
    - Arch Linux
    - Latest Ubuntu
    - Fedora
- MacOS
    - Intel
    - Apple Silicon
- Windows
    - 10 Native
    - 10 WSL 2
    - 11
- Web
    - GitHub Codespaces

**Comment by jwoertink** [comment]
nice! I'm down to test this. How do I install that zip? Unpack it, and move it to some vscode directory? Looks like I have a `~/.vscode/extensions/` directory... Great work on this!

**Comment by nobodywasishere** [comment]
Thank you! To install it, you just need to extract it and install it from within vscode: https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix

Make sure to reload the window after installing to ensure you're running the right version.

**Comment by jwoertink** [comment]
Ok, seeing a few things here... Would you like me to list them out in this thread? or just open up new issues?

**Comment by nobodywasishere** [comment]
We can start with a comment here with a basic overview of the issues you're seeing, including OS information and stuff. From there we can create issues.

**Comment by nobodywasishere** [comment]
Do you have 'mainFile' set in your settings for this workspace?

**Comment by jwoertink** [comment]
I don't have that field set.  
![image](https://github.com/crystal-lang-tools/vscode-crystal-lang/assets/2391/67001a95-056e-41aa-bdb9-74f178f5b443)

Since the main file changes per project, what would be the best way to set this? For example, on each Lucky project, the main file is the name of the project, so if my project is named foo, then my main file would be `src/foo.cr`. I could use `src/start_server.cr`, but then when I'm not in a Lucky project, that wouldn't exist. 

Thinking about it though, it would make things easier if we adopted a single `src/main.cr` for every project always :joy:  Though, `crystal init app test` generates a `src/test.cr` file for the main :thinking:

**Comment by jwoertink** [comment]
Ok, adding that main does seem to solve that issue :+1:

**Comment by nobodywasishere** [comment]
Maybe we can default to `src/project_name.cr` if mainFile isn't set? Also you can have vscode settings be per project afaik, and it'll save it in a '.vscode/settings.json' in the project itself, so you don't need to set it globally for all projects. The documentation/error handling for this could be better.

**Comment by nobodywasishere** [comment]
Oh god I'm sorry! I have no idea what could've caused that, maybe too many instances of the compiler running? Honestly, I'm almost to the point of leaving the current version as-is and moving over to put my efforts into the rewrite. This was really only supposed to be small fixes to make things easier and be a hold-over until the rewrite was stable but now I'm unsure if it's worth it.

**Comment by jwoertink** [comment]
> maybe too many instances of the compiler running

Yeah, I'm pretty sure this is what it was. I was able to run `top` after and saw like 30 crystal compilers that seemed to be doing stuff. Once VSCode was closed, and I waited a few minutes, everything returned to normal. Maybe it was just trying to run a new one on each keystroke or something? We actually had a similar issue in Lucky a while back. There's a built-in watcher and each time you'd save a file, it kicks off a new crystal compiler to recompile the app. The issue was if you made several changes and saved several files, it would kick off a new one for each file saved.

To fix that, we had to basically store the current process, and if a new save comes in, then we just stop that one and do a new one.

https://github.com/luckyframework/lucky/blob/d60191eb057230f8eb2cd4d446ad791742284613/tasks/watch.cr#L159-L198

**Comment by bcardiff** [comment]
> what would be the best way to set this?

Using the shards.yml targets values if they exists seems like a good default. But I am not sure how to deal when there are multiple.

Having an option to use specs as main file (that will require `**/*_spec.cr` on the fly) might be a good checkbox/option to have since that is neither a target in shards.tml nor is usually the case of a single file that includes all specs.

**Comment by nobodywasishere** [comment]
Just added a commit that treats specs as their own main files, ignoring the mainFile if set, when executing implementations/etc. I also reverted enabling completions / implementations / hover as I believe one of them was causing the memory issue and I haven't had the time to investigate which.

**Comment by y8** [comment]
Thanks for the build! 


I'm having issues with build task for a project where `shards.yml` have more than one target. 

For example, I have a list of targets:

```yaml
targets:
  agent:
    main: src/app/agent.cr
  beacon:
    main: src/app/beacon.cr
  server:
    main: src/app/server.cr    
```

And build task: 

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "crystal",
      "command": "run",
      "file": "src/app/beacon.cr",
      "label": "Crystal: run - src/app/beacon.cr",
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

When I'm trying to launch this task I'm getting: 

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "crystal",
      "command": "run",
      "file": "src/app/beacon.cr",
      "label": "Crystal: run - src/app/beacon.cr",
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

It seems like task accept only first target, failing to launch any others. Also it doesn't work with arbitrary files, for example this task that that supposed to run currently open file won't work either: 

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "crystal",
      "command": "run",
      "file": "${file}",
      "problemMatcher": [],
      "label": "Crystal: run current file",
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

Maybe I'm missing something in configuration?

**Comment by nobodywasishere** [comment]
@y8 thank you for the writeup, I'm going to create a separate issue for this
