### ISSUE TITLE
Dot in comments triggers autocomplete.

### ISSUE THREAD

**Issue by RazrFalcon** [crystal-lang-tools/vscode-crystal-lang#178]
**Describe the bug**

When writing comments, each `.` press triggers an autocomplete, which is very annoying.

`crystalline` is enabled, in case it matters. 

**To Reproduce**
1. Create a comment.
2. Press `.`

**Expected behavior**
Autocomplete should be ignored in comments.

**Piece of Code**

```crystal
# comment.
```

**Desktop:**
 - OS: macOS
 - Crystal version: 1.9.2
 - This plugin version: 0.8.4
- `crystalline`:  0.10.0

**Comment by RazrFalcon** [comment]
Yes, seems like `crystalline` issue.

**Comment by nobodywasishere** [comment]
This is now happening without Crystalline.
