### ISSUE TITLE
Extra indentation of def when prefixed with "private"

### ISSUE THREAD

**Issue by Qwerp-Derp** [crystal-lang-tools/vscode-crystal-lang#18]
When I type

```crystal
private def foo
```

And then press Enter, and then type an end, the plugin dedents the `end` once, so I get this:

```crystal
  private def foo
end
```

This also occurs with prefixes of `protected`, and cases:

```crystal
  case foo
when
```

**Comment by faustinoaq** [comment]
Hi, I [use the same](https://github.com/crystal-lang-tools/vscode-crystal-lang/blob/master/src/crystalMain.ts#L15) configuration as [ruby](https://github.com/rubyide/vscode-ruby/blob/master/src/ruby.ts#L17).

So this bug also happens in vscode-ruby and the default ruby support in vscode too.

![Imgur](https://i.imgur.com/wY66iNe.gif)

![Imgur](https://i.imgur.com/bVYcuZo.gif)

As workaround you can disable `autoIndent` in `settings.json`

```
{
  "editor.autoIndent": true
}
```

Thanks for report this issue.
