### ISSUE TITLE
V 0.9 won't catch some errors

### ISSUE THREAD

**Issue by cgimenez** [crystal-lang-tools/vscode-crystal-lang#183]
With this new version, this piece of code

```
@regs_map[reg][:cpu_regs] do |reg|
  reg.free
end
```

Won't catch the missing .each
So when on_save, the offending file goes red for a second, but the extension will not report any error (and prevents the file to be auto formated)

Edit : v0.8.4 catches the error, file goes red, no auto format

**Comment by nobodywasishere** [comment]
I think the issue is the duplicate calls to the findProblemsRaw in the formatting. I'll fix this soon and do a new release. Thank you for reaching out!
