### ISSUE TITLE
Refactoring crystalSymbols

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/vscode-crystal-lang#24]
Currently the [crystalSymbols.ts](https://github.com/crystal-lang-tools/vscode-crystal-lang/blob/master/src/crystalSymbols.ts#L15) is really bad implemented, I need to change that 😅

**Comment by faustinoaq** [comment]
Very useful 👉 https://github.com/SuperPaintman/crystal-ctags

Ctags for Crystal by @SuperPaintman

**Comment by maxbertinetti** [comment]
No more rilevant since work on Scy is on halt.
