### ISSUE TITLE
Shortcut to navigate to beginning and end of block

### ISSUE THREAD

**Issue by scriptnull** [crystal-lang-tools/vscode-crystal-lang#25]
Hi, I am very new to Crystal and I have been barely using it for a week on vs code with this extension.

Good work guys! I would like to suggest some features.

In programming languages, where brackets are used to define the scope, I use `cmd+shift+\` to navigate to the matching bracket.

![go-end-of-block](https://user-images.githubusercontent.com/4211715/31306332-1a7b595c-ab6b-11e7-89ce-0be29371766d.gif)

But in crystal, we don't have brackets and scopes are being defined by `def`, `if` ... `end` etc. So, I would like to have shortcuts to move to beginning and end of scopes.

![image](https://user-images.githubusercontent.com/4211715/31306342-af3b0d6c-ab6b-11e7-90ca-6fcc4d71f6bd.png)

For example, 
- If the shortcut is pressed at line number 30, the cursor would navigate to the end statement at line number 35.
- If the shortcut is pressed at line number 32 ( if statement ), the cursor would navigate to the end statement at line number 34.
- If the shortcut is pressed at line number 31, the cursor would navigate to the end statement at line number 35. ( because that code is in `do-end` block ) -- This is not possible with `cmd+shift+\` in bracket scoped languages. So, this could be optional implementation based on the possibilities.

This is will help in navigating the code base faster. It's as powerful as saying "Go to the next function in the class and modify it. Once done, move to the next function."

**Comment by faustinoaq** [comment]
Hi Thanks you for report this issue!

This problem also happen on VSCode for Ruby, Elixir and other similar languages.

I already published an issue about that on VSCode repo

Please see: https://github.com/Microsoft/vscode/issues/32085

**Comment by nobodywasishere** [comment]
https://github.com/microsoft/vscode/issues/583
