### ISSUE TITLE
Support wildcard on mainFile

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/vscode-crystal-lang#26]
> Support `main_file = "src/*.cr"` as mainFile requiring all in a temp file `crystal tool implementations -C src/foo/bar.cr:line:col /path/for/tmp.cr`

A good recommendation by @Papierkorb

Also see: https://github.com/crystal-lang-tools/scry/issues/29

**Comment by faustinoaq** [comment]
I'm working on something to fix this (at LSP side), I'll publish something very soon :smile:

**Comment by nobodywasishere** [comment]
The underlying crystal tools don't support using wildcards for the main file, so there's nothing to do here. As well, the extension is moving away from using a configuration to set the main file
