### ISSUE TITLE
Add indentation support for `abstract` keyword

### ISSUE THREAD

**Issue by Qwerp-Derp** [crystal-lang-tools/vscode-crystal-lang#28]
## Reproduction:

1. Type this into a `.cr` file in VS Code:

    ```crystal
    abstract class Foo
    ```

2. Press <kbd>Enter</kbd>, and then type

    ```crystal
    end
    ```

## Results:

```crystal
  abstract class Foo
end
```

The `end` is dedented once, as if the `abstract` nullifies the indentation of `class`.

**Comment by faustinoaq** [comment]
Hi @Qwerp-Derp I think `abstract` keyword on `def` doesn't need a `end` because you can't write an implementation on `abstract def`:

```crystal
abstract class Foo
  abstract def foo
end

class Bar < Foo
  def foo
    # implementation
  end
end
```

Also see: https://crystal-lang.org/docs/syntax_and_semantics/virtual_and_abstract_types.html

**Comment by Qwerp-Derp** [comment]
Sorry, wrong one - it was meant to be `abstract class Foo` instead. Will fix right now.

**Comment by faustinoaq** [comment]
![ezgif-5-0c032c2706](https://user-images.githubusercontent.com/3067335/31849476-38a58aea-b608-11e7-8fe1-2beff0c826c2.gif)

Oh, I understand now, https://github.com/crystal-lang-tools/vscode-crystal-lang/pull/29 Fixes this issue :smile:

**Comment by faustinoaq** [comment]
Done 👍 

![ezgif-5-e057e33206](https://user-images.githubusercontent.com/3067335/31850334-d8bb18ee-b615-11e7-98a3-d60681c773c1.gif)

`0.3.6` is published https://marketplace.visualstudio.com/items?itemName=faustinoaq.crystal-lang
