### ISSUE TITLE
Highlight `?` in method definitions consistently

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/vscode-crystal-lang#32]
![screenshot_20171030_201408](https://user-images.githubusercontent.com/3067335/32203047-e4606e24-bdae-11e7-958b-1fb7afd3f15c.png)

see: https://github.com/crystal-lang-tools/sublime-crystal/issues/29

**Comment by faustinoaq** [comment]
![screenshot_20180517_054225](https://user-images.githubusercontent.com/3067335/40172708-14d19a06-5995-11e8-9e80-b0c9f95fa81d.png)

Fixed using custom [tmLanguage](https://github.com/crystal-lang-tools/Crystal.tmbundle) bundle :tada:

**Comment by Proximyst** [comment]
Shouldn't this be closed? @faustinoaq
