### ISSUE TITLE
Crystal compiler not found. Some features can throw errors

### ISSUE THREAD

**Issue by stern0** [crystal-lang-tools/vscode-crystal-lang#33]
I have installed crystal with homebrew and the compiler is in the path below:
```/usr/local/Cellar/crystal-lang/0.23.1_3/src/compiler/crystal```

But keep getting the this error:
```Crystal compiler not found. Some features can throw errors```

**Comment by faustinoaq** [comment]
Try:

```json
{
    "crystal-lang.compiler": "/usr/local/Cellar/crystal-lang/0.23.1_3/src/compiler/crystal"
}
```

Also check the Wiki https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Settings#compiler

**Comment by cryst10** [comment]
@faustinoaq it's the same I had

**Comment by faustinoaq** [comment]
> it's the same I had

Then you can try setting `"crystal-lang.compiler": "crystal"` and be sure `crystal` command is accessible like other user common programs.

Maybe `ln -s "/usr/local/Cellar/crystal-lang/0.23.1_3/src/compiler/crystal" /usr/bin/crystal` ?
