### ISSUE TITLE
Add support functions to syntax highlighting

### ISSUE THREAD

**Issue by hanyuone** [crystal-lang-tools/vscode-crystal-lang#34]
*See [Ruby's highlighting](https://github.com/rubyide/vscode-ruby/blob/master/syntaxes/ruby.tmLanguage#L3004) for more details.*

Built-in functions in Crystal for objects and such, like `.not_nil!` and `push`, should be highlighted using `support.function.core.crystal`.

This can't be directly copied and pasted, since there is a sizeable difference between the two languages in terms of built-in functions.

**Comment by faustinoaq** [comment]
Yeah, Actually this extension is using [crystal.json](https://github.com/crystal-lang-tools/vscode-crystal-lang/blob/master/snippets/crystal.json) generated from [crystal.tmLanguage](https://github.com/crystal-lang-tools/sublime-crystal/blob/master/Crystal.tmLanguage). So if we can improve the syntax highlighting on VSCode, we can improve Sublime as well.

**Comment by Qwerp-Derp** [comment]
Bump @faustinoaq: any updates?

**Comment by faustinoaq** [comment]
Hi @Qwerp-Derp not yet 😅 I have been facing some issues with crystal syntax, looks like some [keywords just broke the highlighting](https://github.com/crystal-lang-tools/vscode-crystal-lang/issues/44).

**Comment by faustinoaq** [comment]
I gonna use official [TextMate Crystal.tmLanguage](https://github.com/crystal-lang-tools/Crystal.tmbundle/blob/master/Syntaxes/Crystal.tmLanguage), although, seems that tmLanguage doesn't highlight those methods either :sweat_smile:  

Anyway, a new syntax file Will be available on next release :wink:
