### ISSUE TITLE
Add support for interpolated strings to syntax highlighting

### ISSUE THREAD

**Issue by Qwerp-Derp** [crystal-lang-tools/vscode-crystal-lang#35]
In something like

```crystal
"#{1 + 2}"
```

the `1` and `2` should be highlighted as integers, and the `+` should be highlighted as an operator. The `#{}` may be optionally highlighted.

**Comment by faustinoaq** [comment]
![screenshot_20171108_055245](https://user-images.githubusercontent.com/3067335/32545233-0bf30d02-c449-11e7-8985-d02ab030f393.png)

`theme dark+ | vscode 1.17.2`

What VSCode version are you using?

I'm using `1.17.2` and the interpolation highlight on default themes works well.

The only thing is not highlighted is the operator :)

**Comment by Qwerp-Derp** [comment]
Sorry, I was using a different colour scheme, will close the issue. It works fine on Atom One Dark for VSCode.
