### ISSUE TITLE
Crystal compiler not found. spawn

### ISSUE THREAD

**Issue by Dillybob1992** [crystal-lang-tools/vscode-crystal-lang#43]
Hey! Awesome extension! Having a bit of trouble getting the crystal compiler to work 

I set my user settings to:

```
{
    "crystal-lang.compiler": "\"C:/Users/Administrator/Desktop/bash.exe\" & crystal"
}
```

However, i'm getting `Crystal compiler not found. spawn "C:/Users/Administrator/Desktop/bash.exe" & crystal ENOENT`

I'm not sure if there is a guide anywhere, but how exactly do we "link" to our crystal compiler since we're using the Unix Subsystem?

**Comment by Dillybob1992** [comment]
Aww, so I just saw this tutorial:

https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Settings

Changed setting to 
```
{
    "crystal-lang.bashOnWindows": true,
    "crystal-lang.compiler": "crystal.bat"
}
```
Restarted VSCode. However, now no error shows, and the formatting doesn't change

**Comment by Dillybob1992** [comment]
Looks like in Visual Studio code the formatting doesn't happen on CTRL+S, you have to right click -> Format. But it works, didn't see that guide at the bottom

**Comment by faustinoaq** [comment]
Hi @Dillybob1992, Thanks for try this extension!, we have some basic features but there is [a lot of work to do](https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Roadmap) yet

> Looks like in Visual Studio code the formatting doesn't happen on CTRL+S

VSCode doesn't have format-on-save activated by default, you need to enable it using:

```json
// settings.json
{
  "editor.formatOnSave": true,
}
```
