### ISSUE TITLE
forall seems to break syntax

### ISSUE THREAD

**Issue by ghost** [crystal-lang-tools/vscode-crystal-lang#44]
Example:

<img width="398" alt="screen shot 2018-01-16 at 00 29 36" src="https://user-images.githubusercontent.com/5178184/34969120-5bae122e-fa54-11e7-8180-c37d1a4eac27.png">

Looks like it's somehow related to the parentheses? Wrapping the return value in parens "fixes" it:

<img width="360" alt="screen shot 2018-01-16 at 00 30 19" src="https://user-images.githubusercontent.com/5178184/34969144-77a6e546-fa54-11e7-9c2e-7c2609b9d5ba.png">

**Comment by faustinoaq** [comment]
Good catch!

I think this issue is related to https://github.com/crystal-lang-tools/vscode-crystal-lang/pull/9

BTW, Do you know if sublime text have this issue?

**Comment by Proximyst** [comment]
I would like to add how this works fine:
```crystal
    def convert?(input : String) : T? forall T
      converter = ConversionManager.global_converters![T.name]
      converter ||= convert
    end
```

![picture of proof in the editor](https://my-owo-was.banned.today/863009.png)

This however only cursives the method in question instead of everything:
```crystal
      def inner! : TypeConverter(T) forall T
        @inner.as TypeConverter(T)
      end
```
[!picture of proof in the editor](https://owo.whats-th.is/646813.png)

**Comment by Proximyst** [comment]
The fact there are no issues on it so far indicates it most likely isn't there. You could however try to type out the snippet yourself.

I by the way found out why the `inner!` method had cursive, and that's as the `initialize` method uses `forall` as well, but is an empty method.
```crystal
module Cropt
  module Internal
    struct TypeConverter
      def initialize(@inner : Cropt::TypeConverter(T)) forall T
      end

      def inner! : TypeConverter(T) forall T
        @inner.unsafe_as TypeConverter(T)
      end
    end
  end
end
```

**Comment by faustinoaq** [comment]
> An alternative is replacing current json file and return back to tmLanguage file, but I don't know if ST has this issue as well sweat_smile
>> The fact there are no issues on it so far indicates it most likely isn't there.

So, I think I gonna replace my custom [crystal.json](https://github.com/crystal-lang-tools/vscode-crystal-lang/blob/master/syntaxes/crystal.json) syntax by official [TextMate Crystal.tmLanguage](https://github.com/crystal-lang-tools/Crystal.tmbundle/blob/master/Syntaxes/Crystal.tmLanguage) or Sublime [Crystal.tmLanguage](https://github.com/crystal-lang-tools/sublime-crystal/blob/master/Crystal.tmLanguage) :sweat_smile: WDYT?

**Comment by faustinoaq** [comment]
![screenshot_20180517_042606](https://user-images.githubusercontent.com/3067335/40168938-6bd48eb8-598a-11e8-83be-2d6a9cc4f389.png)

Looks like is working fine with  [TextMate Crystal.tmLanguage](https://github.com/crystal-lang-tools/Crystal.tmbundle/blob/master/Syntaxes/Crystal.tmLanguage) :tada: 

Will be available on next release :wink:

**Comment by Proximyst** [comment]
That looks great. Thanks for the look into the issue ^^

**Comment by faustinoaq** [comment]
next minor version 0.3.11 (available soon on vscode marketplace) fixes this (thanks to @icyleaf)
