### ISSUE TITLE
Replace json syntax files by tmLanguage used on Sublime Text package

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/vscode-crystal-lang#51]
Hi community, I have ben busy latest weeks, I hope I can pull some commits this weekend

I'm maintaining the `crystal-syntax.json` file responsible of syntax highlighting, but there is some issues I don't really know how to fix, so I think if VSCode have out-the-box support for `.tmLanguage` then would be a nice idea to use it

![screenshot_20180406_122031](https://user-images.githubusercontent.com/3067335/38434689-e7055826-3994-11e8-8f87-a8f377a089eb.png)

I think it would be easier to maintain both, sublime-text  and VSCode highlighting, since both will use the same file.

I don't  know if atom can use `tmLanguage` files as well, @keplersj Do you know something about this? :sweat_smile:

**Comment by keplersj** [comment]
Atom cannot use `tmLanguage` files, it converts them to a similar JSON format.  See [Creating a Grammar](https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/) in the [Atom Flight Manual](https://flight-manual.atom.io/).

However if you were to maintain the JSON formatted grammar in https://github.com/crystal-lang-tools/language-crystal, and create a pipeline to build to `tmLanguage`, you'd be able to hit GitHub Syntax Highlight, Atom, VSCode, and TextMate in one grammar.
