### ISSUE TITLE
Crystal support in Markdown code blocks

### ISSUE THREAD

**Issue by fgimian** [crystal-lang-tools/vscode-crystal-lang#56]
Hey Faustino, hope life is treating you well 😄 

It's possible to inject a code block configuration for Markdown files using the methods shown at https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example

At the moment, Crystal code blocks are not syntax highlighted in Markdown files.

Would you consider incorporating this into your extension?

Thanks!
Fotis

**Comment by fgimian** [comment]
I've just got this working so I'll send a pull request soon when I test it more buddy 😄

**Comment by nobodywasishere** [comment]
I have this working on [this branch](https://github.com/nobodywasishere/vscode-crystal-lang/tree/markdown_code_block):

![image](https://github.com/crystal-lang-tools/vscode-crystal-lang/assets/32797552/b6539994-6745-43d0-88a9-cf8123f8b585)
