### ISSUE TITLE
scry shows error but seems that autocompletion fails

### ISSUE THREAD

**Issue by cocodrino** [crystal-lang-tools/vscode-crystal-lang#61]
Hi...good day, first thank you for this project and scry, seems really promising, my issue is that seems scry can find the issues in my code but if I try autocomplete not show any completition

my config is
```js

"crystal-lang.compiler": "/home/yo/.crenv/shims/crystal",
"crystal-lang.problems": "build",
"crystal-lang.completion": true,
"crystal-lang.server": "/usr/bin/scry",
"crystal-ide.backend": "custom",
"crystal-ide.customCommand": "/usr/bin/scry",
"crystal-lang.hover": true

```

if I change in amber a code like this
```rb
pets = Pet.all
#change to
pets=Pet.allx #show error [Scry] undefined method 'allx' for Pet:Class great!!

#now...if I press ctr+space when I'm in the l letter
pets=Pet.al| 
#scry completes with ApplicationController...which is not ok



```

would be possible fix the autocomplete system??? thank you so much!!!

**Comment by faustinoaq** [comment]
Hi @cocodrino Scry auto-complete is still work in progress, please see: https://github.com/crystal-lang-tools/scry/issues/66

**Comment by cocodrino** [comment]
oh that is sad...well I've suscribed to [that](https://github.com/crystal-lang-tools/scry/issues/66) for get informed when it'll be available, hope this will be soon :sob:  ...thank you...
