### ISSUE TITLE
Where is compiler path?

### ISSUE THREAD

**Issue by 98-f355-f1** [crystal-lang-tools/vscode-crystal-lang#62]
I am using Linux Debian on Windows WSL.
I use VS Code and have got crystal, dependencies and LLVM compiler installed, it works on the flagship, Hello World!.

I have now installed this extension, but cant figure out where the compiler path goes for the llvm.
I put in the example, "crystal-lang.compiler": "/usr/bin/crystal/bin", clearly this is not the compiler path...

Since the wsl kind of discreetly hides everything, as we are not allowed to modify any files in the system. A file search hasn't really help me locate it.

Thanks

**Comment by faustinoaq** [comment]
Hi @98-f355-f1 Thanks you for using Crystal, this extension is still a big work in progress :wink: 

On WSL you need a bat script to execute crystal via `bash.exe`, please see wiki: https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Settings#bashonwindows

**Comment by 98-f355-f1** [comment]
I'll check it out.  I can use Crystal perfectly well with Debian bash and VSC, it's just those pesky error messages in code that is a nuisance, and have been playing around a bit.  I was able to convert some number crunching functions from Ruby to Crystal with a little effort... as I was learning about the strict type system.  Since I needed a big number, I found the BigInt type... works great, but a little bit tedious to declare and instantiate every single variable that the algorithm touches as to not get a TypeError.

I am going to do my own benchmarking against MRI, JRuby, straight C and Crystal.. from what I've seen from others I'd expect C to win by a nose over Crystal, but handily beat MRI and JRuby.  I will also start figuring out how to benchmarking on C ext. in MRI vs. Crystal out of the box, and Crystal with C ext.  Should be fun.

How do I become a contributor to your code base?  I am a newcomer, but learning fast.

Thanks again

**Comment by 98-f355-f1** [comment]
BTW, is this the compiler???

I copied the whole path from my windows C: all the way into the Debian WSL file system and ends at the "user path" \src\compiler\crystal\crystal.cr ..... this seems to have killed the warning and error messages, is the right file?
Or is it in the next folder of crystal at ...\crystal\ where this is compiler_path.cr, compiler.cr ??

Although, I got a weird popup when I reloaded VSC after resetting the path and asked how I want to associate .cr files, of course I put VSC, but thats the first time that I have been asked this question... LOL.

**Comment by 98-f355-f1** [comment]
@faustinoaq 
I think that I missed this part:

**On WSL you need a bat script to execute crystal via bash.exe, please see wiki: https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Settings#bashonwindows**

I just installed Crystal from the Linux tarballs...  I will install and let you know if it all worked.

**Comment by 98-f355-f1** [comment]
Error messages resolved

Great 👍 

Issue closed
