### ISSUE TITLE
Crystal compiler not found after upgrade vscode to 1.26.0

### ISSUE THREAD

**Issue by TsumiNa** [crystal-lang-tools/vscode-crystal-lang#63]
Microsoft/vscode#56659

Hi! I got some issue when use this extension in vscode 1.26.0 or higher.
My crystal version is 0.26.0

**Comment by faustinoaq** [comment]
Hi @TsumiNa, Do you still have this issue?

**Comment by watzon** [comment]
I'm having this issue on Debian with Code 1.35. I'm using asdf version manager to install crystal, but I did try including the absolute path to crystal in the settings and it didn't work

**Comment by dprobinson** [comment]
I'm having the same problem too. VSCode 1.34 with Crystal 0.28.0 (installed from Arch repos at /usr/bin/crystal). I've also tried changing the path in the settings to no avail.

**Comment by watzon** [comment]
@faustinoaq seems like this needs to be reopened.

**Comment by fabon-f** [comment]
@faustinoaq  Why didn't you commit this solution(https://github.com/crystal-lang-tools/vscode-crystal-lang/issues/86#issuecomment-462048696) to master branch yet? Is there any problems?

**Comment by fabon-f** [comment]
In my case, executing `crystal env` in `crystalUtils.ts`(js) caused an error like this.

> Error: Command failed: /usr/local/bin/crystal env
Missing ENV key: "HOME" (KeyError)
  from Path::home:Path
  from Path#expand<String>:Path
  from File::expand_path<String>:String
  from Crystal::CacheDir#compute_dir:String
  from Crystal::Command#run:(Bool | Crystal::Compiler::Result | Nil)
  from main
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues

When I add `{ cwd: ROOT, env: CRENV, stdio: ["ignore", "pipe", "pipe"] }` as second argument of `execSync`, the error disappeared.
