### ISSUE TITLE
Add "endwise" functionality?

### ISSUE THREAD

**Issue by hanyuone** [crystal-lang-tools/vscode-crystal-lang#64]
There's a package [`endwise`](https://github.com/kaiwood/vscode-endwise) on the VSCode marketplace that automatically adds an `end` to every block. Should this functionality also be implemented within this plugin?

**Comment by faustinoaq** [comment]
Hi @Qwerp-Derp , Nice functionality, I think we can add this to https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Useful-extensions :+1: 

Feel free to edit it, is like wikipedia :wink:

**Comment by faustinoaq** [comment]
Oh, I just realize endwise only support Ruby :sweat_smile:

**Comment by faustinoaq** [comment]
Please check https://github.com/kaiwood/vscode-endwise/pull/20 :wink:
