### ISSUE TITLE
Support crystal tools format

### ISSUE THREAD

**Issue by mrkaspa** [crystal-lang-tools/vscode-crystal-lang#66]
I have instaled crystal 0.26 but it does not support crystal formatting built in tool, I have it but it is not working

**Comment by faustinoaq** [comment]
Hi @mrkaspa

Currently formatting is failing because some changes in crystal itself, see #80 

I'm working on a quick fix, also future major version will use [Scry](https://github.com/crystal-lang-tools/scry/) :+1:
