### ISSUE TITLE
Add support for annotations

### ISSUE THREAD

**Issue by Heaven31415** [crystal-lang-tools/vscode-crystal-lang#68]
This [PR](https://github.com/crystal-lang/crystal/pull/6063) introduced user-defined annotations. Right now it's legal to write something like that:

```crystal
annotation Foo
end
``` 

However **vscode-crystal-lang** implementation doesn't cover that. For example there is no syntax highlighting or anything else that may be required (it's not supported even on github).

**Comment by faustinoaq** [comment]
Fixed by #76
