### ISSUE TITLE
Invalid type names in crystalCompletionData.ts

### ISSUE THREAD

**Issue by Heaven31415** [crystal-lang-tools/vscode-crystal-lang#69]
If you go here: [link](https://github.com/crystal-lang-tools/vscode-crystal-lang/blob/8e2ed71f76417eec11533764981b2063469342f7/src/crystalCompletionData.ts#L991) you can see that lines from 991 to 994 are using invalid unsigned integer type names. For example instead of **UInt16** there is **Uint16**.

**Comment by faustinoaq** [comment]
Yeah, `crystalCompletionData.ts` was a workaround to get basic completion working, I need to refactor some things and implement Scry :sweat_smile: https://github.com/crystal-lang-tools/scry/issues/66
