### ISSUE TITLE
Problem with syntax highlighting

### ISSUE THREAD

**Issue by Heaven31415** [crystal-lang-tools/vscode-crystal-lang#70]
As it's easy to see in the screenshot, word **type** has wrong colour. It's treated as if it were a keyword, not a regular variable/parameter name.

![invalid_hightlighting](https://user-images.githubusercontent.com/16988850/47052335-1c0b1780-d1a8-11e8-825e-5b2754d5a34b.png)

**Comment by icyleaf** [comment]
It fixed in #76

**Comment by faustinoaq** [comment]
Hi @Heaven31415 Sorry for late reply, I already merged @icyleaf PR, new version is comming :sweat_smile:
