### ISSUE TITLE
Scry crashes if workspace not loaded with .cr file

### ISSUE THREAD

**Issue by matthewmcgarvey** [crystal-lang-tools/vscode-crystal-lang#79]
Scry will work if the workspace is opened with a crystal file in the editor already, but if there is no file in the editor or it is not a crystal file, scry will crash once a crystal file is opened and this extension loads.  I can not get the error message from the scry process.  This failure happens with both master and the release of this extension and using the master branch of scry.  This is probably an issue in scry but I came here first to try to get an idea of what kind of error is happening.

**Comment by faustinoaq** [comment]
I think this is an issue in Scry, I'm working on migrating this extension to use scry by default, so lets keep this issue open until I figure out the solution.

Thank you for report it :+1:
