### ISSUE TITLE
why vscode update my crystal lang extension without my permission?

### ISSUE THREAD

**Issue by girng** [crystal-lang-tools/vscode-crystal-lang#87]
now all the variables inside my methods are light blue, not white

i do not like this and never asked vscode to update to the latest version :/

is it possible for me to change this? i mean everything was working just fine for nearly a year, it was perfect! 😿 😭

**Comment by faustinoaq** [comment]
Hi @girng You can disable it on `settings.json`:

```json
{
 "extensions.autoUpdate": false
}
```

> now all the variables inside my methods are light blue, not white

Yeah, I'm working on a new syntax file, based on sublime-crystal one :sweat_smile: 

BTW, you can install any version of vscode-crystal-lang if you want:

![image](https://user-images.githubusercontent.com/3067335/52862763-03821e00-3104-11e9-8a0f-92069ad1ea1b.png)

![image](https://user-images.githubusercontent.com/3067335/52862800-201e5600-3104-11e9-860d-da32b930c67c.png)


Recently added here https://github.com/Microsoft/vscode/issues/12764

**Comment by girng** [comment]
yeah, when i click on install previous version the top bar just fades in and out really fast (issue with vscode probably). i made an issue in their repo.  thanks for the help

**Comment by girng** [comment]
and really @faustinoaq i love your plugin.. not an issue with the plugin itself really, just i hate change lol. i have so much crystal code already and when i see new colors it just makes me more confused. i prob just have to get used to it.
