### ISSUE TITLE
Why do we need crystal-windows-installer when WSL can be enabled by changing one line?

### ISSUE THREAD

**Issue by Pyroglyph** [crystal-lang-tools/vscode-crystal-lang#88]
You mention [here in the wiki](https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Settings#bashonwindows) that in order to use WSL with this extension we need to install the crystal-windows-installer package (which requires WSL to work anyway), but I've found that isn't the case at all.

If `shell: "bash"` is added to `spawnOptions` in [this file](https://github.com/crystal-lang-tools/vscode-crystal-lang/blob/master/src/crystalUtils.ts#L63) then it magically starts working through WSL.

I've posted this as a question instead of just submitting a PR because I have zero experience with extension development and there may well be a valid reason for not doing it this way. Is there?

**Comment by faustinoaq** [comment]
Hi @Pyroglyph Thank you for this issue!

> If `shell: "bash"` is added to `spawnOptions` in this file then it magically starts working through WSL.

Great idea, I haven't tried that, let me test it! :+1:
