### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by Indribell** [crystal-lang-tools/vscode-crystal-lang#97]
The plugin currently is overriding the indentation set by Visual Studio Code.

Any code formatting result in a 2 spaces indentation, when the editor is set on 4. This means any file that is formatted by ctrl+alt+i, gets its indentation overridden by the plugin.

Please follow the settings indicated by the editor and do not override the choice set by the user.

>  "editor.insertSpaces": true,
>  "editor.tabSize": 4,

**Comment by denolfe** [comment]
The current implementation pipes the code into the `crystal tool format` command. It appears that custom indentation width is not supported by that command, so this would have to be entirely custom.

**Comment by maxbertinetti** [comment]
I soon start to analyze any enhancements request.

**Comment by maxbertinetti** [comment]
I think it's best, as in other languages, to follow a rule about indentation for making code from different source homogeneus
